CIELCH_Doc: CIELCHColour Class Reference
CIELCHColour Class Reference
This class extends the JUCE Colour class by adding support for the CIE LCH perceptual colour space.
Public Member Functions
CIELCHColour () noexcept
Creates a transparent black colour.
CIELCHColour (const Colour &colour) noexcept
Creates a CIELCHColour object from a Colour objet.
CIELCHColour (const CIELCHColour &other) noexcept
Creates a copy of another CIELCHColour object.
CIELCHColour (uint32 argb) noexcept
Creates a colour from a 32-bit ARGB value.
CIELCHColour (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
CIELCHColour (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
CIELCHColour (uint8 red, uint8 green, uint8 blue, float alpha) noexcept
Creates a colour from 8-bit red, green, and blue values, and a floating-point alpha.
CIELCHColour (float hue, float saturation, float brightness, uint8 alpha) noexcept
Creates a colour using the HSV colour space.
CIELCHColour (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using using the HSV colour space.
CIELCHColour (PixelARGB argb) noexcept
Creates a colour using a PixelARGB object.
CIELCHColour (PixelRGB rgb) noexcept
Creates a colour using a PixelRGB object.
CIELCHColour (PixelAlpha alpha) noexcept
Creates a colour using a PixelAlpha object.
CIELCHColour & operator= (const CIELCHColour &other) noexcept
Copies another CIELCHColour object.
CIELCHColour & operator= (const Colour &other) noexcept
Copies from a Colour object.
float getCIELightness () const noexcept
Returns the CIE lightness component.
float getCIEChroma () const noexcept
Returns the CIE chroma/saturation component.
float getCIEHue () const noexcept
Returns the CIE hue component.
void getCIELCH (float &L, float &C, float &H) const noexcept
Returns the CIE lightness, chroma/saturation and hue.
CIELCHColour withCIELightness (float newLightness, bool &imaginary) const noexcept
Returns a copy of this colour with a different CIE brightness.
CIELCHColour withCIEChroma (float newChroma, bool &imaginary) const noexcept
Returns a copy of this colour with a different CIE chroma/saturation.
CIELCHColour withCIEHue (float newHue, bool &imaginary) const noexcept
Returns a copy of this colour with a different CIE hue.
CIELCHColour withMultipliedCIELightness (float amount, bool &imaginary) const noexcept
Returns a copy of this colour with its CIE Lightness multiplied by the given value.
CIELCHColour withMultipliedCIEChroma (float multiplier, bool &imaginary) const noexcept
Returns a copy of this colour with its CIE chroma/saturation multiplied by the given value.
CIELCHColour withRotatedCIEHue (float amountToRotate, bool &imaginary) const noexcept
Returns a copy of this colour with its CIE hue rotated.
CIELCHColour CIELighter (bool &imaginary, float amountBrighter=0.4f) const noexcept
Returns a brighter version of this colour.
CIELCHColour CIEDarker (bool &imaginary, float amountDarker=0.4f) const noexcept
Returns a darker version of this colour.
Static Public Member Functions
static CIELCHColour fromCIELCH (float L, float C, float H, float alpha, bool &imaginary) noexcept
Create the colour from the CIE LCH colour space.
static void RGBtoXYZ (CIELCHColour c, float &X, float &Y, float &Z) noexcept
Convert from the sRGB colour space to the XYZ colour space.
static void XYZtoRGB (float X, float Y, float Z, CIELCHColour &c, bool &imaginary) noexcept
Convert from the XYZ colour space to the sRGB colour space.
static void XYZtoCIELab (float X, float Y, float Z, float &L, float &a, float &b) noexcept
Convert from the XYZ colour space to the CIE Lab colour space.
static void CIELabtoXYZ (float L, float a, float b, float &X, float &Y, float &Z) noexcept
Convert from the CIE Lab colour space to the XYZ colour space.
static void CIELabtoCIELCH (float L, float a, float b, float &Lout, float &C, float &H) noexcept
Convert from the CIE Lab colour space to the CIE LCH colour space.
static void CIELCHtoCIELab (float L, float C, float H, float &Lout, float &a, float &b) noexcept
Convert from the CIE LCH colour space to the CIE Lab colour space.
static void CIELCHtoRGB (float L, float C, float H, CIELCHColour &c, bool &imaginary) noexcept
Convert from the CIE LCH colour space to the sRGB colour space.
static void RGBtoCIELCH (CIELCHColour c, float &L, float &C, float &H) noexcept
Convert from the sRGB colour space to the CIE LCH colour space.
Detailed Description
This class extends the JUCE Colour class by adding support for the CIE LCH perceptual colour space.
The CIE LCH colour space is a colour space, which reflects how humans perceive colours. Therefore interpolating colours in CIE LCH gives smoother variations than when using HSV/HSL. LCH is an abbreviation for Lightness, Chroma(Saturation) and Hue. Note that the LCH colour space contains more colours than humans can see. Therefore it is possible, that a LCH colour cannot be converted to an exact RGB colour. In such a case, the closest RGB approximation is used.
Internally The CIE LCH colour space uses the CIE Lab and the CIE XYZ colour spaces. So you find functions for those as well. But not that many, because the focus is on CIE LCH.
See also https://en.wikipedia.org/wiki/CIE_1931_color_space and https://en.wikipedia.org/wiki/Lab_color_space.
Here an example on how to use the class:
CIELCHColour colour = Colours::yellow;
float l, c, h;
colour.getCIELCH(l, c, h);
float newSaturation = c / 2.0f;
bool imaginary;
CIELCHColour newColour = CIELCHColour::fromCIELCH(l, newSaturation, h, colour.getAlpha(), imaginary);
if (imaginary)
   std::cout << "Imaginary colour. RGB values have been clipped to the visible range";
Because the CIELCHColour class is subclassing the JUCE::Colour class, it has all its functionality. It is e.g. perfectly OK to write:
CIELCHColour newColour  = CIELCHColour::fromHSV(h, s,  v);
CIELCHColour newColour2 = Colours::yellow;
Constructor & Destructor Documentation
CIELCHColour::CIELCHColour () noexcept
Creates a transparent black colour.
Referenced by XYZtoRGB().
CIELCHColour::CIELCHColour (const Colour & colour) noexcept
Creates a CIELCHColour object from a Colour objet.
CIELCHColour::CIELCHColour (const CIELCHColour & other) noexcept
Creates a copy of another CIELCHColour object.
CIELCHColour::CIELCHColour (uint32 argb) explicit noexcept
Creates a colour from a 32-bit ARGB value.
The format of this number is: ((alpha << 24) | (red << 16) | (green << 8) | blue).
All components in the range 0x00 to 0xff. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque.
See also
getPixelARGB
CIELCHColour::CIELCHColour (uint8 red, uint8 green, uint8 blue) noexcept
Creates an opaque colour using 8-bit red, green and blue values.
CIELCHColour::CIELCHColour (uint8 red, uint8 green, uint8 blue, uint8 alpha) noexcept
Creates a colour using 8-bit red, green, blue and alpha values.
CIELCHColour::CIELCHColour (uint8 red, uint8 green, uint8 blue, float alpha) noexcept
Creates a colour from 8-bit red, green, and blue values, and a floating-point alpha.
Alpha of 0.0 is transparent, alpha of 1.0f is opaque. Values outside the valid range will be clipped.
CIELCHColour::CIELCHColour (float hue, float saturation, float brightness, uint8 alpha) noexcept
Creates a colour using the HSV colour space.
Floating point hue, saturation and brightness values, and an 8-bit alpha.
The floating point values must be between 0.0 and 1.0. An alpha of 0x00 is completely transparent, alpha of 0xff is opaque. Values outside the valid range will be clipped.
CIELCHColour::CIELCHColour (float hue, float saturation, float brightness, float alpha) noexcept
Creates a colour using using the HSV colour space.
Floating point hue, saturation, brightness and alpha values.
All values must be between 0.0 and 1.0. Numbers outside the valid range will be clipped.
CIELCHColour::CIELCHColour (PixelARGB argb) noexcept
Creates a colour using a PixelARGB object.
This function assumes that the argb pixel is not premultiplied.
CIELCHColour::CIELCHColour (PixelRGB rgb) noexcept
Creates a colour using a PixelRGB object.
CIELCHColour::CIELCHColour (PixelAlpha alpha) noexcept
Creates a colour using a PixelAlpha object.
Member Function Documentation
CIELCHColour & CIELCHColour::operator= (const CIELCHColour & other) noexcept
Copies another CIELCHColour object.
CIELCHColour & CIELCHColour::operator= (const Colour & other) noexcept
Copies from a Colour object.
CIELCHColour CIELCHColour::fromCIELCH (float L, float C, float H, float alpha, bool & imaginary) static noexcept
Create the colour from the CIE LCH colour space.
The CIE LCH colour space is a colour space, which corresponds to the way humans perceive colours. It uses the components Lightness, Chroma (Saturation) and Hue. So in that way it is similar to the HSV colour space. But the HSV colour space is not perceptually correct. Note that the LCH colour space contains more colours than humans can see. These "imaginary" colours cannot be represented by RGB colours. Therefore certain LCH colours cannot be converted to a RGB colour. In such a case, the returned RGB colour is the closest match to the CIE LCH colour. And the parameter "imaginary" is set to true.
Parameters
[in] L = lightness in the range [0...1]
[in] C = chroma, relative saturation in the range [0...1]
[in] H = hue in the range [0...1]
[in] alpha = the alpha value for the colour.
[out] imaginary = true if the LCH colour is imaginary (see above). False otherwise.
References CIELCHtoRGB().
Referenced by withCIEChroma(), withCIEHue(), withCIELightness(), withMultipliedCIEChroma(), withMultipliedCIELightness(), and withRotatedCIEHue().
float CIELCHColour::getCIELightness () const noexcept
Returns the CIE lightness component.
The value is in the range 0...1
References getCIELCH().
Referenced by CIEDarker(), and CIELighter().
float CIELCHColour::getCIEChroma () const noexcept
Returns the CIE chroma/saturation component.
The value is in the range 0...1
References getCIELCH().
float CIELCHColour::getCIEHue () const noexcept
Returns the CIE hue component.
The value is in the range 0...1
References getCIELCH().
void CIELCHColour::getCIELCH (float & L, float & C, float & H) const noexcept
Returns the CIE lightness, chroma/saturation and hue.
All values are in the range 0...1.
References RGBtoCIELCH().
Referenced by getCIEChroma(), getCIEHue(), getCIELightness(), withCIEChroma(), withCIEHue(), withCIELightness(), withMultipliedCIEChroma(), withMultipliedCIELightness(), and withRotatedCIEHue().
CIELCHColour CIELCHColour::withCIELightness (float newLightness, bool & imaginary) const noexcept
Returns a copy of this colour with a different CIE brightness.
If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
CIELighter, CIEDarker, withMultipliedCIELightness
fromCIELCH for a better explanation on imaginary.
References fromCIELCH(), and getCIELCH().
Referenced by CIEDarker(), and CIELighter().
CIELCHColour CIELCHColour::withCIEChroma (float newChroma, bool & imaginary) const noexcept
Returns a copy of this colour with a different CIE chroma/saturation.
If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
fromCIELCH for a better explanation on imaginary.
References fromCIELCH(), and getCIELCH().
CIELCHColour CIELCHColour::withCIEHue (float newHue, bool & imaginary) const noexcept
Returns a copy of this colour with a different CIE hue.
If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
fromCIELCH for a better explanation on imaginary.
References fromCIELCH(), and getCIELCH().
CIELCHColour CIELCHColour::withMultipliedCIELightness (float amount, bool & imaginary) const noexcept
Returns a copy of this colour with its CIE Lightness multiplied by the given value.
The new colour's brightness is (this->getCIELightness() * multiplier) (the result is clipped to legal limits). If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
fromCIELCH for a better explanation on imaginary. Note: in a CIELCH space, the only way to create a truly black colour is by setting both lightness and chroma to zero. If you only set lightness to zero, the colour might still be visible.
References fromCIELCH(), and getCIELCH().
CIELCHColour CIELCHColour::withMultipliedCIEChroma (float multiplier, bool & imaginary) const noexcept
Returns a copy of this colour with its CIE chroma/saturation multiplied by the given value.
The new colour's chroma is (this->getCIEChroma() * multiplier) (the result is clipped to legal limits). If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
withMultipliedCIEChroma, withRotatedCIEHue
fromCIELCH for a better explanation on imaginary.
References fromCIELCH(), and getCIELCH().
CIELCHColour CIELCHColour::withRotatedCIEHue (float amountToRotate, bool & imaginary) const noexcept
Returns a copy of this colour with its CIE hue rotated.
The new colour's hue is ((this->getCIEHue() + amountToRotate) % 1.0) If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
withMultipliedCIELightness, withMultipliedCIEChroma
fromCIELCH for a better explanation on imaginary.
References fromCIELCH(), and getCIELCH().
CIELCHColour CIELCHColour::CIELighter (bool & imaginary, float amountBrighter = 0.4f) const noexcept
Returns a brighter version of this colour.
Parameters
amountBrighter how much brighter to make it - a value from 0 to 1.0 where 0 is unchanged, and higher values make it brighter
imaginary If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true.
See also
fromCIELCH for a better explanation on imaginary.
withMultipliedCIELightness
References getCIELightness(), and withCIELightness().
CIELCHColour CIELCHColour::CIEDarker (bool & imaginary, float amountDarker = 0.4f) const noexcept
Returns a darker version of this colour.
Parameters
amountDarker how much darker to make it - a value from 0 to 1.0 where 0 is unchanged, and higher values make it darker
imaginary If the returned colour is an imaginary colour, then the "imaginary" parameter is set to true. Note: in a CIELCH space, the only way to create a real truly black colour is by setting both lightness and chroma to zero. If you only set lightness to zero, the colour might still be visible.
See also
fromCIELCH for a better explanation on imaginary.
withMultipliedCIELightness
References getCIELightness(), and withCIELightness().
void CIELCHColour::RGBtoXYZ (CIELCHColour c, float & X, float & Y, float & Z) static noexcept
Convert from the sRGB colour space to the XYZ colour space.
The transformations are calculated for Observer = 2 and Illuminant = D65. For explanation and formulas see https://en.wikipedia.org/wiki/SRGB
Parameters
[in] c = the (RGB) colour to convert
[out] X = in the range 0....95.047
[out] Y = in the range 0....100.000
[out] Z = in the range 0....108.883
Referenced by RGBtoCIELCH().
void CIELCHColour::XYZtoRGB (float X, float Y, float Z, CIELCHColour & c, bool & imaginary) static noexcept
Convert from the XYZ colour space to the sRGB colour space.
Note that the XYZ colour space contains more colours than humans can see. These "imaginary" colours cannot be represented by standard RGB colours. Therefore certain XYZ colours cannot be converted to a RGB colour. In such a case, the returned RGB colour is the closest match to the XYZ colour. And the parameter "imaginary" is set to true.
The transformations are calculated for Observer = 2 and Illuminant = D65. For explanation and formulas see https://en.wikipedia.org/wiki/SRGB
Parameters
[in] X = in the range 0....95.047
[in] Y = in the range 0....100.000
[in] Z = in the range 0....108.883
[out] c = the resulting (RGB) colour
[out] imaginary true if the XYZ colour is imaginary (see above). False otherwise.
References CIELCHColour().
Referenced by CIELCHtoRGB().
void CIELCHColour::XYZtoCIELab (float X, float Y, float Z, float & L, float & a, float & b) static noexcept
Convert from the XYZ colour space to the CIE Lab colour space.
The transformations are calculated for Observer = 2 and Illuminant = D65. For epxlanation and formulas see https://en.wikipedia.org/wiki/Lab_color_space
Parameters
[in] X = in the range 0....95.047
[in] Y = in the range 0....100.000
[in] Z = in the range 0....108.883
[out] L = lightness in the range 0...100
[out] a = range 0...500
[out] b = range 0...200
Referenced by RGBtoCIELCH().
void CIELCHColour::CIELabtoXYZ (float L, float a, float b, float & X, float & Y, float & Z) static noexcept
Convert from the CIE Lab colour space to the XYZ colour space.
The transformations are calculated for Observer = 2 and Illuminant = D65. For epxlanation and formulas see https://en.wikipedia.org/wiki/Lab_color_space
Parameters
[in] L = lightness in the range 0...100
[in] a = range 0...500
[in] b = range 0...200
[out] X = in the range 0....95.047
[out] Y = in the range 0....100.000
[out] Z = in the range 0....108.883
Referenced by CIELCHtoRGB().
void CIELCHColour::CIELabtoCIELCH (float L, float a, float b, float & Lout, float & C, float & H) static noexcept
Convert from the CIE Lab colour space to the CIE LCH colour space.
Basically, this is a conversion to cylindrical coordinates. For explanation and details see https://en.wikipedia.org/wiki/Lab_color_space.
Parameters
[in] L = lightness in the range 0...100
[in] a = range 0...500
[in] b = range 0...200
[out] Lout = lightness in the range 0...100
[out] C = chroma, relative saturation in the range 0...134
[out] H = hue in the range 0...360
Referenced by RGBtoCIELCH().
void CIELCHColour::CIELCHtoCIELab (float L, float C, float H, float & Lout, float & a, float & b) static noexcept
Convert from the CIE LCH colour space to the CIE Lab colour space.
Basically, this is a conversion from cylindrical to carthesian coordinates. For explanation and details see https://en.wikipedia.org/wiki/Lab_color_space.
Parameters
[in] L = lightness in the range 0...100
[in] C = chroma, relative saturation in the range 0...134
[in] H = hue in the range 0...360
[out] Lout = lightness in the range 0...100
[out] a = range 0...500
[out] b = range 0...200
Referenced by CIELCHtoRGB().
void CIELCHColour::CIELCHtoRGB (float L, float C, float H, CIELCHColour & c, bool & imaginary) static noexcept
Convert from the CIE LCH colour space to the sRGB colour space.
The CIE LCH colour space is a colour space, which corresponds to the way humans perceive colours. It uses the components Lightness, Chroma (Saturation) and Hue. So in that way it is similar to the HSV colour space. But the HSV colour space is not perceptually correct. Note that the LCH colour space contains more colours than humans can see. These "imaginary" colours cannot be represented by standard RGB colours. Therefore it is possible, that a LCH colour cannot be converted to a RGB colour.
Parameters
[in] L = lightness in the range [0...1]
[in] C = chroma, relative saturation in the range [0...1]
[in] H = hue in the range [0...1]
[out] c = a JUCE colour component.
[out] imaginary true if the LCH colour is imaginary (see above). False otherwise.
References CIELabtoXYZ(), CIELCHtoCIELab(), and XYZtoRGB().
Referenced by fromCIELCH().
void CIELCHColour::RGBtoCIELCH (CIELCHColour c, float & L, float & C, float & H) static noexcept
Convert from the sRGB colour space to the CIE LCH colour space.
The CIE LCH colour space is a colour space, which corresponds to the way humans perceive colours. In contrast the HSV colour space is not perceptually correct.
Parameters
[in] c = a JUCE colour component.
[out] L = lightness in the range [0...1]
[out] C = chroma, relative saturation in the range [0...1]
[out] H = hue in the range [0...1]
References CIELabtoCIELCH(), RGBtoXYZ(), and XYZtoCIELab().
Referenced by getCIELCH().
The documentation for this class was generated from the following files:
D:/Programming/Audio/CIELCH/CIELCHColour_Git/module/CIELCHColour.h
D:/Programming/Audio/CIELCH/CIELCHColour_Git/module/CIELCHColour.cpp